#include "1P.h"
#include "eak.h"
#include "Lv.h"
#include "Str.h"
#include "Timer.h"
#include "Sco.h"
#include "re.h"
#include "score.h"
#include "bg_a.h"
#include "bg_b.h"
#include "bg_c.h"

#include "face1.h"
#include "face2.h"
#include "face3.h"
#include "face4.h"
#include "face5.h"
#include "face6.h"
#include "face7.h"
#include "face8.h"

#include "TextCursor.h"

#include "Hex.h"

#include "web.h"

#include "box1.h"
#include "box2.h"
#include "box3.h"
#include "box4.h"

#include "Play.h"
#include "Again.h"
#include "ED.h"
#include "To.h"
#include "rn.h"
#include "Retu.h"
#include "PAUS.h"
#include "Menu.h"
#include "Game.h"
#include "GAME2.h"
#include "Exit.h"

#include "Fish.h"
#include "PUZZ2.h"
#include "LE3.h"
#include "WIN.h"
#include "LOSE.h"
#include "Next.h"

#include "diamond.h"
