# /*************************  MATRIX ADVANCE  ****************************\
# *  Copyright (c) 2005 Vincent E. Milum Jr., All rights reserved.        *
# *                                                                       *
# *  See License.txt for more information                                 *
# *                                                                       *
# *  Latest Source versions can be found at:  HTTP://WWW.DARKAIN.COM/     *
# \***********************************************************************/


BUILDPATH	:= ../build
OUTFILE		:= screens.a
include $(CURDIR)/../make.inc